name: CI/CD Pipeline
on:
  pull_request:
    types: [opened, closed]
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run basic-test
        #continue-on-error: false

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    # needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t your-docker-repo/image-name:latest .
          docker push your-docker-repo/image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS ECS
        uses: aws-actions/aws-ecs-deploy@v2
        with:
          cluster: your-ecs-cluster
          service: your-ecs-service
          images: your-docker-repo/image-name:latest
          run-task: true

  merge-check:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check test status
        run: |
          if [ ${{ job.status }} != 'success' ]; then
            echo "Tests failed. Cannot merge the pull request."
            exit 1
          else
            echo "Tests passed. Ready to merge."
          fi
